name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get install -y asciidoc asciidoc-dblatex pandoc

    - name: Build HTML
      run: make html

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Pascal Tutorial
        path: |
                pascal_tutorial2.html
                pascal_tutorial.html
                pandoc.css

